---
title: "Introduction to R"
author: "Santi Novani & Muhammad Apriandito"
---

# Welcome to R

```{r}
# This is a chunk, A place where you can write an run your code
print("Hello World")
```

# Mathematical Operation

```{r}
# Addition
5 + 5
```

```{r}
# Subtraction
5 - 5
```

```{r}
# Multiplication
3 * 5
```

```{r}
# division
5 / 2
```

```{r}
# Power
2^5
```

```{r}
# Modulo
28 %% 6
```

# Variable Assignment

```{r}
# Creating variable using "<-"
example1 <- 4
```

```{r}
# Print variable 
print(example1)
```

```{r}
# Creating variable using "="
example2 = 2
```

```{r}
# Print variable
print(example2)
```

```{r}
# Example in using variable
price <- 2000
quantity <- 3
```

```{r}
# Calculate total price
total_price <- price * quantity
```

```{r}
# Print total price
print(total_price)
```

# Data Type

# Numeric
```{r}
# Examples of numeric data types
n <- 1.2

# Find out the data type using class()
class(n)
```

# Integer
```{r}
# Examples of numeric data types
i <- 2L

# Find out the data type using class()
class(i)
```

```{r}
# Convert numeric to integer
i_from_n <- as.integer(n)

# Find out the data type using class()
class(i_from_n)
```

# Character
```{r}
# Examples of character data types
c <- "SBM - ITB"

# Find out the data type using class()
class(c)
```

# Logical
```{r}
# Examples of logical data types
log <- TRUE

# Find out the data type using class()
class(log)
```

# Complex
```{r}
# Examples of logical data types
com <- 3 + 2i

# Find out the data type using class()
class(com)
```

# Data Structure

# Vector 
```{r}
# Example of vector
v <- c(1, 2, 3)
```

```{r}
# Print vector example
print(v)
```

# List
```{r}
# Example of list
l <- list(1, "a", TRUE, 1 + 4i)
```

```{r}
# Print list example
print(l)
```

# Matrix 
```{r}
# Example of Matrix
m <- matrix(c(1:3))
```

```{r}
# Print matrix example
print(m)
```

# Factor
```{r}
# Example of Factor
f <- factor(c("Fashion", "Kuliner", "Media", "Otomotif", "Media", "Kuliner"))
```

```{r}
# Print factor example
print(f)
```

# Dataframe
```{r}
# Example of Dataframe
df <- data.frame(
  Nama = c("Aditya", "Ayush", "Akshay"),
  Usia = c(26, 26, 27),
  BB = c(81, 85, 90),
  Tinggi = c(157,186, 165),
  Salary = c(5000, 6000, 7500)
)
```

```{r}
# Print datframe example
print(df)
```

# Function

## Built in Function
```{r}
# Creating a Vector containing age data
age <- c(22, 23, 21, 8, 10, 14, 15)
```

```{r}
# Calculating average age
mean(age)
```

## User Defined Function
```{r}
# Function to calculate return on investment
roi <- function(total_pendapatan, biaya, investasi_awal) {
  return(((total_pendapatan - biaya)/investasi_awal)*0.1)
}
```

```{r}
# Using ROI function
roi(175, 75, 75)
```

# Package

## Readr
```{r}
# Install package
install.packages("readr")
```

```{r}
# Load package
library(readr)
```

```{r}
# import "marketing.csv" dataset from "data" directory
df_csv <- read_csv("data/marketing.csv")
```
```{r}
# Print data
print(df_csv)
```


## Readxl
```{r}
# Install package
install.packages("readxl")
```

```{r}
# Load package
library(readxl)
```

```{r}
# import "marketing.csv" dataset from "data" directory
df_xlsx <- read_xlsx("data/marketing.xlsx")
```

```{r}
# Print data
print(df_xlsx)
```
