---
title: "Descriptive Statistics"
author: "Santi Novani & Muhammad Apriandito"
---

## Install Packages
```{r}
# Install packages from CRAN
install.packages("pastecs")
```

```{r}
# Install packages from GitHub
remotes::install_github("easystats/easystats")
```

## Load Packages
```{r}
# Load Packages
library(readr) # We already installed it in the previous module
library(easystats)
library(pastecs)
```

## Load Data
```{r}
# Load data
df_marketing <- read_csv("data/marketing.csv")
```

```{r}
# Print/Show the data
print(df_marketing)
```

## Descriptive Statistics
```{r}
# Descriptive Statistics using base (You don't need to install anything)
summary(df_marketing)
```

```{r}
# Descriptive Statistics using pastecs
stat.desc(df_marketing)
```

```{r}
# Get Statistical Report using easystats
report(df_marketing)
```

## Correlation

```{r}
# Compute a correlation matrix using base (You don't need to install anything)
cor(df)
```

### Visualize
```{r}
# Install package
install.packages("ggcorrplot")
```

```{r}
# Load package
library(ggcorrplot)
```

```{r}
# Visualize using ggcorplot
ggcorrplot(cor(df))
```

