```{r}
library(tidymodels)
```

```{r}
# load in the data set
data(gss)
```

```{r}
glimpse(gss)
```

```{r}
gss %>%
  specify(response = age)
```

```{r}
gss %>%
  specify(age ~ partyid)
```
```{r}
# with the named arguments
gss %>%
  specify(response = age, explanatory = partyid)
```

```{r}
gss %>%
  specify(college ~ partyid, success = "degree") %>%
  hypothesize(null = "independence")
```

```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40)
```

```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 5000, type = "bootstrap")
```

```{r}
gss %>%
  specify(partyid ~ age) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 5000, type = "permute")
```

```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "mean")
```

```{r}
gss %>%
  specify(age ~ college) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 5000, type = "permute") %>%
  calculate("diff in means", order = c("degree", "no degree"))
```

