---
title: "Multiple linear regression"
author: "Santi Novani & Muhammad Apriandito"
---

# Install Packages
```{r}
# Install Packages
install.packages("tidyverse")
```

# Load Packages
```{r}
# Load Packages
library(easystats) # We already installed it in the previous module
library(tidyverse)
```

# Load Data
```{r}
# Load data
df <- read_csv("data/marketing.csv")
```

```{r}
# Print/Show the data
print(df)
```

```{r}
# Statistical Report
report(marketing)
```

```{r}
# Check Correlation
correlation(marketing)
```

# Build Regression Model
```{r}
# Create Model
model <- lm(sales ~ youtube + facebook + newspaper, data = marketing)
```

```{r}
# Check Parameter
model_parameters(model)
```

```{r}
# Plot Parameters
plot(parameters(model))
```

```{r}
# Model Report
report(model)
```

# Classical Asumption Test
```{r message=FALSE, warning=FALSE}
# Check Model Assumsition
check_model(model)
```

```{r}
# Check Normality
check_normality(model)
```

```{r}
# Check Heteroscedasticity
check_heteroscedasticity(model)
```

```{r}
# Check multicollineariy
check_collinearity(model)
```

```{r}
# Check Autocorrelation
check_autocorrelation(model)
```

```{r}
# Model Performance
model_performance(model)
```

