---
title: "Cluster Analysis"
author: "Santi Novani & Muhammad Apriandito"
---

# Install Package
```{r}
install.packages("factoextra")
```

# Load Packages
```{r}
# Load package
library(tidyverse) 
library(cluster) 
library(factoextra)
```

# Import Data
```{r}
# Import data
df <- read_csv2("data/income-spend.csv")
```

# Explorasi Data
```{r}
# Show the data
print(df)
```

```{r}
# Descriptive Statistics
summary(df)
```

```{r}
# Visualize with scatter plot
  ggplot(data = df, aes(x = Income, y = Spending)) +
  geom_point()
```

# Data Preprocessing
```{r}
# Select Data
df_cluster <-  df %>%
  select(Income, Spending)

head(df_cluster)
```

# Find out the optimal number of cluster
```{r}
# Finding the optimal number of clusters with the silhouette method
fviz_nbclust(df_cluster, kmeans, method = "silhouette")
```

# K-Means Clustering
```{r}
# Cluster Analysis with K-Means
cluster <- kmeans(df_cluster, centers = 2, nstart = 25)
cluster
```

# Visualisasi Cluster
```{r}
# Visualizing the cluster
fviz_cluster(cluster, 
             data = df_cluster, 
             geom = "point", 
             stand = FALSE)
```